### ISSUE TITLE
USER STORY: Create account, login, logout

### ISSUE THREAD

**Issue by cbstange** [cbstange/b-social#1]
As a user, I can create a unique profile/account which I can log in and out of with a password so my photos are stored and protected.

**Acceptance Criteria:**

1. Start page includes a login and signup button.
 
2.  User can create unique username and password.

3. User can log out of their account.

**Tasks**

- [] Add a log in and sign up button to home page

- [] Add fields to create a username and password

- [] Add log out button to nav bar.
