### ISSUE TITLE
USER STORY: Create option to upload a new photo.

### ISSUE THREAD

**Issue by cbstange** [cbstange/b-social#3]
As a user I can upload

**Acceptance Criteria:**

1. Nav bar and profile page have button to upload a photo
 
2.  User can delete pictures from their profile

3. Option to add a caption

**Tasks:**

- [] Add upload button to nav bar
- [] Add caption field to upload process
- [] Add button to delete a photo
